# -*- coding: utf-8 -*-
{
    'name': 'Jinasena : MasterData : Purchase',
    'version': '17.0.0.0.2',
    'summary': 'Master-data extracted from CDB for Purchase domain.',
    'description': 'Extracted from Clear-DB. Test-env master data. Edit the CSVs in data/ to add/remove rows before install.',
    'author': 'Jinasena Agricultural Machinery (Pvt) Ltd.',
    'category': 'Extra Tools',
    'license': 'LGPL-3',
    'depends': [
        'BugFix-Purchase',
        'Jinasena_MasterData_Common',
        'Jinasena_MasterData_Accounting',
        'Jinasena_MasterData_Stock',
    ],
    'data': [
        'data/res_partner.csv',
        'data/x_delivery_terms.csv',
        'data/x_delivery_term_charge.csv',
        'data/x_payment_methods.csv',
        'data/x_misc_charge_codes.csv',
        'data/x_non_inventory_produc.csv',
        'data/x_import_charges.csv',
        'data/x_import_rfq_charge_he.csv',
        'data/x_import_rfq_charge_li.csv',
        'data/x_tariff_date.csv',
        'data/x_tariff_rates.csv',
        'data/x_tariffmaster.csv',
        'data/x_trf_charges.csv',
        'data/x_trf_duty.csv',
        'data/x_trf_taxes.csv',
        'data/x_structure_master.csv',
        'data/x_structure_details.csv',
        'data/x_imports_ledger_setup.csv',
        'data/x_vendor_group.csv',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
